name: Publish GitHub Packages
description: Action to publish npm packages to GitHub Packages

inputs:
  version:
    description: "Version of npm package"
    required: true
  auth_token:
    description: "Pass secrets.GITHUB_TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure .npmrc to deploy GitHub Packages
      shell: bash
      run: |
        cat << EOF > .npmrc
        @koumatsumoto:registry=https://npm.pkg.github.com/
        //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
        EOF
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth_token }}

    - name: Publish package
      shell: bash
      run: npm version --no-commit-hooks --no-git-tag-version --allow-same-version ${{ inputs.version }} && npm publish --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.auth_token }}

    - uses: ./.github/actions/get-package-info
      id: package_info

    - name: Create Job Summary
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.auth_token }}
        script: |
          const heading = 'New GitHub Packages'
          const output = `
            *New Version* 🤖 *${{ inputs.version }}*\n
            Run \`npm install ${{ steps.package_info.outputs.package_name }}@${{ steps.package_info.outputs.package_version }}\`\n
          `;
          await core.summary
            .addHeading(heading)
            .addRaw(output)
            .write()
